//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcFotograf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLBLOGYORUM
    {
        public int ID { get; set; }
        public Nullable<int> BLOGID { get; set; }
        public string ADSOYAD { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string YORUM { get; set; }
        public Nullable<bool> DURUM { get; set; }
    
        public virtual TBLBLOG TBLBLOG { get; set; }
    }
}
