//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcFotograf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPERSONEL
    {
        public int ID { get; set; }
        public string ADSOYAD { get; set; }
        public string MESLEK { get; set; }
        public string INSTAGRAM { get; set; }
        public string RESIM { get; set; }
    }
}
